routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('subdomain', '^((?!www|mailing).)*$');

Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
    Route::get('login', 'AuthSubscriber\LoginController@showLoginForm')->name('subscriber.login');
    Route::post('login', 'AuthSubscriber\LoginController@login');
    Route::post('logout', 'AuthSubscriber\LoginController@logout')->name('subscriber.logout');
    Route::get('password/reset', 'AuthSubscriber\ForgotPasswordController@showLinkRequestForm')->name('subscriber.password.request');
    Route::post('password/email', 'AuthSubscriber\ForgotPasswordController@sendResetLinkEmail')->name('subscriber.password.email');
    Route::get('password/reset/{token}', 'AuthSubscriber\ResetPasswordController@showResetForm')->name('subscriber.password.reset');
    Route::post('password/reset', 'AuthSubscriber\ResetPasswordController@reset')->name('subscriber.password.update');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth:subscriber'], function () {
    Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
        Route::get('/', 'DashboardController@formateurIndex')->name('formateur.index');
        Route::prefix('formation/{url}')->group(function () {
            Route::get('/', 'FormationController@formationSubscriber')->name('formateur.formation');
            Route::prefix('module/{module}')->group(function () {
                Route::get('/', 'ModuleController@moduleSubscriber')->name('formateur.module');
                Route::get('chapter/{chapter}', 'ChapterController@chapterSubscriber')->name('formateur.chapter');
            });
        });
    });
});

Route::group(['middleware' => ['auth:web', 'verified']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('mailservers', 'MailserverController');
    Route::resource('senders', 'SenderController');
    Route::resource('newsletters', 'NewsletterController');
    Route::resource('tags', 'TagController');
    Route::resource('subscribers', 'SubscriberController');
    Route::resource('forms', 'FormController');
    Route::resource('schedules', 'ScheduleController');
    Route::resource('campaigns', 'CampaignController');
    Route::resource('formations', 'FormationController');
    Route::resource('fields', 'FieldController');

    Route::prefix('formation/{formation}')->group(function () {
        Route::post('students', 'FormationController@storeStudents')->name('students.store');
        Route::get('students', 'FormationController@indexStudents')->name('students.index');
        Route::get('students/edit', 'FormationController@editStudents')->name('students.edit');
        Route::resource('modules', 'ModuleController');
        Route::prefix('module/{module}')->group(function () {
            Route::resource('chapters', 'ChapterController');
            Route::get('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwyg')->name('chapters.wysiwyg');
            Route::patch('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwygUpdate')->name('chapters.wysiwyg.update');
        });
    });

    Route::get('forms/{form}/wysiwyg', 'FormController@wysiwyg')->name('forms.wysiwyg');
    Route::patch('forms/{form}/wysiwyg', 'FormController@wysiwygUpdate')->name('forms.wysiwyg.update');
    Route::get('queues', 'QueueController@index')->name('queues.index');
    Route::get('queues/schedule/{schedule}', 'QueueController@showSchedule')->name('queues.schedule');
    Route::get('queues/subscriber/{subscriber}', 'QueueController@showSubscriber')->name('queues.subscriber');
    Route::get('queues/newsletter/{newsletter}', 'QueueController@showNewsletter')->name('queues.newsletter');
    Route::delete('queues/{queue}', 'QueueController@destroy')->name('queues.destroy');
    Route::get('campaigns/{campaign}/automate', 'CampaignController@automate')->name('campaigns.automate');
    Route::patch('campaigns/{campaign}/automate', 'CampaignController@automateUpdate')->name('campaigns.automate.update');
});

app/Campaign.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    protected $fillable = [
        'name', 'user_id', 'trigger', 'trigger_value', 'executed', 'tags_type'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function form()
    {
        return $this->belongsTo('App\Form', 'trigger_value');
    }

    public function campaignSteps()
    {
        return $this->hasMany('App\CampaignStep');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function scopeTriggeredByForm($query, $form_id)
    {
        return $query->where(['trigger' => 'new_form_sub', 'trigger_value' => $form_id]);
    }

    public function scopeReadyTriggeredByDate($query)
    {
        return $query->where(['trigger' => 'at_date', 'executed' => false])->whereDate('trigger_value', '<=', Carbon::now());
    }

    public function scopeOwned($query)
    {
        return $query->where('campaigns.user_id', Auth::id());
    }

    public function delete()
    {
        $this->campaignSteps()->delete();
        parent::delete();
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use App\CampaignStep;
use Illuminate\Http\Request;
use Auth;

class CampaignController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Campaign::class);
    }

    public function index()
    {
        return view('campaign.index');
    }

    public function create()
    {
        return view('campaign.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'trigger' => 'required|in:at_date,new_form_sub',
            'trigger_value' => 'required',
            'tags_type' => 'required_if:trigger,at_date|in:alltags,all,once',
        ];
        $request->validate($rules);
        $campaign = new Campaign($request->all());
        $campaign->user_id = Auth::id();
        $campaign->save();
        $campaign->tags()->sync($request->tags);
        return redirect()->route('campaigns.automate', $campaign->id)->with('success', __('Campagne créée'));
    }

    public function show(Campaign $campaign)
    {
        //
    }

    public function edit(Campaign $campaign)
    {
        return view('campaign.edit', ['campaign' => $campaign]);
    }

    public function update(Request $request, Campaign $campaign)
    {
        $rules = [
            'name' => 'required',
            'trigger' => 'required|in:at_date,new_form_sub',
            'trigger_value' => 'required',
            'tags_type' => 'required_if:trigger,at_date|in:alltags,all,once',
        ];
        $request->validate($rules);
        $campaign->update($request->all());
        $campaign->tags()->sync($request->tags);
        return redirect()->route('campaigns.index')->with('success', __('Campagne mise à jour'));
    }

    public function destroy(Campaign $campaign)
    {
        $campaign->delete();
        return redirect()->route('campaigns.index')->with('success', __('Campagne supprimée'));
    }

    public function automate(Campaign $campaign)
    {
        return view('campaign.automate', ['campaign' => $campaign]);
    }

    public function automateUpdate(Request $request, Campaign $campaign)
    {
        $newsletters = $request->step['newsletter_id'];
        $delay = $request->step['delay'];
        foreach ($newsletters as $key => $newsletter) {
            $campaign_step = CampaignStep::updateOrCreate(
                ['order' => $key, 'campaign_id' => $campaign->id],
                ['newsletter_id' => $newsletter, 'delay' => $delay[$key] ? $delay[$key] : 0]
            );
        }
        return redirect()->route('campaigns.index')->with('success', __('Etapes de Campagne mises à jour'));
    }
}

resources/views/campaign/automate.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Campagne'), $campaign->name], 'new_btn_link' => ''])
<div class="row">
    <div id="page-container">
        <div id="page" class="shadow">
            {!! Form::open([ 'method'  => 'patch', 'route' => [ 'campaigns.automate.update', $campaign->id ], 'autocomplete' => 'off' ]) !!}
                <div id="campaign-steps-container">
                    <div id="click-to-add">{!! __('Cliquez pour ajouter une étape') !!}</div>
                    <ul id="campaign-steps-ul" class="list-group">
                    @foreach($campaign->campaignSteps as $campaignstep)
                        <li class="step">
                            <i class="fas fa-sort step-handle step-options"></i>
                            <i class="fas fa-times step-delete step-options"></i>
                            <div class="step-params">
                                <div class="form-row">
                                    <div class="form-group col-sm-6">
                                        {!! Form::label('newsletter_id', __('Envoyer la newsletter'), ['class' => 'col-form-label']) !!}
                                        {!! Form::select('step[newsletter_id][]', Auth::user()->newsletters()->where('type', 'news')->pluck('newsletters.name', 'newsletters.id'), $campaignstep->newsletter_id, ['class' => 'form-control']) !!}
                                    </div>
                                    <div class="form-group col-sm-6">
                                        {!! Form::label('human_delay', __('Après'), ['class' => 'col-form-label']) !!}
                                        {!! Form::hidden('step[delay][]', $campaignstep->delay, ['class' => 'delay']) !!}
                                        {!! Form::text('human_delay', null, ['class' => 'durationpicker form-control', 'placeholder' => __('Immediatement')]) !!}
                                    </div>
                                </div>
                            </div>
                            <i class="fas fa-plus add-step-before step-options"></i>
                            <i class="fas fa-plus add-step-after step-options"></i>
                        </li>
                    @endforeach
                    </ul>
                </div>
                <button type="submit" class="btn btn-primary btn-block">{!! __('Enregistrer') !!}</button>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        $(function(){
            step = '<li class="step">\
                <i class="fas fa-sort step-handle step-options"></i>\
                <i class="fas fa-times step-delete step-options"></i>\
                <div class="step-params">\
                    <div class="form-row">\
                        <div class="form-group col-sm-6">\
                            {!! Form::label('newsletter_id', __('Envoyer la newsletter'), ['class' => 'col-form-label']) !!}\
                            {!! Form::select('step[newsletter_id][]', Auth::user()->newsletters()->where('type', 'news')->pluck('newsletters.name', 'newsletters.id'), null, ['class' => 'form-control']) !!}\
                        </div>\
                        <div class="form-group col-sm-6">\
                            {!! Form::label('human_delay', __('Après'), ['class' => 'col-form-label']) !!}\
                            {!! Form::hidden('step[delay][]', null, ['class' => 'delay']) !!}\
                            {!! Form::text('human_delay', null, ['class' => 'durationpicker form-control', 'placeholder' => __('Immediatement')]) !!}\
                        </div>\
                    </div>\
                </div>\
                <i class="fas fa-plus add-step-before step-options"></i>\
                <i class="fas fa-plus add-step-after step-options"></i>\
            </li>';
            function isEmpty(){
                if( !$.trim( $('#campaign-steps-container > #campaign-steps-ul').html() ).length ) {
                    $('#campaign-steps-container > #click-to-add').show();
                }else{
                    $('#campaign-steps-container > #click-to-add').hide();
                }
            }
            
            function init(){
                $('.durationpicker').timeDurationPicker({
                    lang: 'fr_FR',
                    defaultValue: function(element) {
                        return element.siblings('.delay').val();
                    },
                    onSelect: function(element, seconds, duration) {
                        element.siblings('.delay').val(seconds);
                        element.val(duration);
                    },
                    years: false,
                    months: false,
                    days: true,
                    hours: true,
                    minutes: true,
                    seconds: false,
                });
            }

            isEmpty();
            init();

            $('#click-to-add').click(function(){
                $('#campaign-steps-ul').append(step);
                isEmpty();
                init();
            })

            $('#campaign-steps-container > #campaign-steps-ul').on('click', '.add-step-after', function(){
                $(this).closest('.step').after(step);
                init();
            })

            $('#campaign-steps-container > #campaign-steps-ul').on('click', '.add-step-before', function(){
                $(this).closest('.step').before(step);
                init();
            })

            $('#campaign-steps-container > #campaign-steps-ul').on('click', '.step-delete', function(){
                $(this).closest('.step').remove();
                isEmpty();
            })

            $('#campaign-steps-container > #campaign-steps-ul').sortable({
                revert: true,
                placeholder: "ui-state-highlight",
                handle: ".step-handle",
                axis: "y",
                start: function(e, ui){
                    ui.placeholder.height(ui.item.height());
                },
                helper: "clone",
            });
        })
    </script>
@endsection

resources/views/campaign/create.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Campagne'), __('Nouveau')], 'new_btn_link' => ''])
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow">
            <div class="card-body">
                {!! Form::open([ 'method'  => 'POST', 'route' => [ 'campaigns.store' ], 'autocomplete' => 'off' ]) !!}
                    <div class="form-group row">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                        <div class="col-sm-6">
                            {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : ''), 'required' => 'required']) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('trigger', __('Déclencheur'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                        <div class="col-sm-6">
                            {!! Form::select('trigger', ['at_date' => __('À la date'), 'new_form_sub' => 'Nouveau inscrit au formulaire'], null, ['class' => 'form-control'.($errors->has('mailserver_id') ? ' is-invalid' : ''), 'required' => 'required']) !!}
                            @if ($errors->has('trigger'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger') !!}</strong>
                                </span>
                            @endif
                            <div class="trigger-params-container new_form_sub">
                                {!! Form::select('trigger_value', Auth::user()->forms()->pluck('forms.name', 'forms.id'), null, ['class' => 'trigger-params form-control'.($errors->has('trigger_value') ? ' is-invalid' : ''), 'disabled' => 'disabled']) !!}
                                @if ($errors->has('trigger_value'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger_value') !!}</strong>
                                </span>
                            @endif
                            </div>
                            <div class="trigger-params-container at_date">
                                {!! Form::text('trigger_value', null, ['class' => 'trigger-params form-control datetimepicker'.($errors->has('trigger_value') ? ' is-invalid' : ''), 'disabled' => 'disabled']) !!}
                                @if ($errors->has('trigger_value'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger_value') !!}</strong>
                                </span>
                            @endif
                            </div>
                        </div>
                    </div>
                    <div class="trigger-params-container at_date">
                        <div class="form-group row">
                            {!! Form::label('tags', __('Tags'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                            <div class="col-sm-6">
                                {!! Form::select('tags_type', ['alltags' => __('Tous les tags'), 'all' => __('Qui ont tous les tags suivants'), 'once' => __('Qui ont au moins un des tags suivants'),], null, ['class' => 'trigger-params form-control'.($errors->has('tags_type') ? ' is-invalid' : '')]) !!}
                                @if ($errors->has('tags_type'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('tags_type') !!}</strong>
                                    </span>
                                @endif
                                {!! Form::select('tags[]', Auth::user()->tags->pluck('name', 'id'), null, ['class' => 'trigger-params form-control'.($errors->has('tags') ? ' is-invalid' : ''), 'multiple' => 'multiple', 'disabled' => 'disabled']) !!}
                                @if ($errors->has('tags'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('tags') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="offset-sm-4 col-sm-6 text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        $(function(){
            var trigger = $('select[name="trigger"]').val();
            $('.trigger-params-container').hide();
            $('.trigger-params').prop('disabled', true);
            $('.'+trigger).find('.trigger-params').prop('disabled', false);
            $('.'+trigger).show();

            $('select[name="trigger"]').change(function(){
                var trigger = $('select[name="trigger"]').val();
                $('.trigger-params-container').hide();
                $('.trigger-params').prop('disabled', true);
                $('.'+trigger).find('.trigger-params').prop('disabled', false);
                $('.'+trigger).show();

                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })



            var tags_type = $('select[name="tags_type"]').val();
            if(tags_type == 'alltags'){
                $('select[name="tags[]"]').prop('disabled', true);
            }else{
                $('select[name="tags[]"]').prop('disabled', false);
            }

            $('select[name="tags_type"]').change(function(){
                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })
        })
    </script>
@endsection

resources/views/campaign/edit.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Campagne'), $campaign->name], 'new_btn_link' => ''])
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow">
            <div class="card-body">
                {!! Form::open([ 'method'  => 'patch', 'route' => [ 'campaigns.update', $campaign->id ], 'autocomplete' => 'off' ]) !!}
                    <div class="form-group row">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                        <div class="col-sm-6">
                            {!! Form::text('name', $campaign->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : ''), 'required' => 'required']) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('trigger', __('Déclencheur'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                        <div class="col-sm-6">
                            {!! Form::select('trigger', ['at_date' => __('À la date'), 'new_form_sub' => 'Nouveau inscrit au formulaire'], $campaign->trigger, ['class' => 'form-control'.($errors->has('mailserver_id') ? ' is-invalid' : ''), 'required' => 'required']) !!}
                            @if ($errors->has('trigger'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger') !!}</strong>
                                </span>
                            @endif
                            <div class="trigger-params-container new_form_sub">
                                {!! Form::select('trigger_value', Auth::user()->forms()->pluck('forms.name', 'forms.id'), ($campaign->trigger == 'new_form_sub' ? $campaign->trigger_value : null), ['class' => 'trigger-params form-control'.($errors->has('trigger_value') ? ' is-invalid' : ''), 'disabled' => 'disabled']) !!}
                                @if ($errors->has('trigger_value'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger_value') !!}</strong>
                                </span>
                            @endif
                            </div>
                            <div class="trigger-params-container at_date">
                                {!! Form::text('trigger_value', ($campaign->trigger == 'at_date' ? $campaign->trigger_value : null), ['class' => 'trigger-params form-control datetimepicker'.($errors->has('trigger_value') ? ' is-invalid' : ''), 'disabled' => 'disabled']) !!}
                                @if ($errors->has('trigger_value'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('trigger_value') !!}</strong>
                                </span>
                            @endif
                            </div>
                        </div>
                    </div>
                    <div class="trigger-params-container at_date">
                        <div class="form-group row">
                            {!! Form::label('tags', __('Tags'), ['class' => 'col-sm-4 col-form-label text-md-right']) !!}
                            <div class="col-sm-6">
                                {!! Form::select('tags_type', ['alltags' => __('Tous les tags'), 'all' => __('Qui ont tous les tags suivants'), 'once' => __('Qui ont au moins un des tags suivants'),], $campaign->tags_type, ['class' => 'trigger-params form-control'.($errors->has('tags_type') ? ' is-invalid' : '')]) !!}
                                @if ($errors->has('tags_type'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('tags_type') !!}</strong>
                                    </span>
                                @endif
                                {!! Form::select('tags[]', Auth::user()->tags->pluck('name', 'id'), $campaign->tags, ['class' => 'trigger-params form-control'.($errors->has('tags') ? ' is-invalid' : ''), 'multiple' => 'multiple', 'disabled' => 'disabled']) !!}
                                @if ($errors->has('tags'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('tags') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="offset-sm-4 col-sm-6 text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        $(function(){
            var trigger = $('select[name="trigger"]').val();
            $('.trigger-params-container').hide();
            $('.trigger-params').prop('disabled', true);
            $('.'+trigger).find('.trigger-params').prop('disabled', false);
            $('.'+trigger).show();

            $('select[name="trigger"]').change(function(){
                var trigger = $('select[name="trigger"]').val();
                $('.trigger-params-container').hide();
                $('.trigger-params').prop('disabled', true);
                $('.'+trigger).find('.trigger-params').prop('disabled', false);
                $('.'+trigger).show();

                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })



            var tags_type = $('select[name="tags_type"]').val();
            if(tags_type == 'alltags'){
                $('select[name="tags[]"]').prop('disabled', true);
            }else{
                $('select[name="tags[]"]').prop('disabled', false);
            }

            $('select[name="tags_type"]').change(function(){
                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })
        })
    </script>
@endsection

resources/views/campaign/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.page-header', ['breadcrumb' => [__('Campagnes')], 'new_btn_link' => route('campaigns.create')])

    <div class="table-responsive shadow">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>{!! __('Nom') !!}</th>
                    <th>{!! __('Déclencheur') !!}</th>
                    <th>{!! __('Valeur') !!}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Auth::user()->campaigns as $row)
                <tr class="trigger-options">
                    <td>{!! $row->name !!}</td>
                    <td>
                        @if($row->trigger == 'new_form_sub')    {!! __('Nouveau inscrit au formulaire') !!}
                        @elseif($row->trigger == 'at_date')    {!! __('À la date') !!}
                        @endif
                    </td>
                    <td>
                        @if($row->trigger == 'new_form_sub')    {!! $row->form->name !!}
                        @elseif($row->trigger == 'at_date')    {!! $row->trigger_value !!}
                        @endif
                    </td>
                    <td>
                        <div class="options-hover float-right">
                            <a href="{!!route('campaigns.automate', $row->id)!!}"><i class="fas fa-file-alt text-dark"></i></a>
                            <a href="{!!route('campaigns.edit', $row->id)!!}"><i class="fas fa-edit text-dark"></i></a>
                            <i class="fas fa-trash-alt delete-submit-form text-dark"></i>
                            {!! Form::open([ 'method'  => 'delete', 'route' => [ 'campaigns.destroy', $row->id ] ]) !!}{!! Form::close() !!}
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection