routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('subdomain', '^((?!www|mailing).)*$');

Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
    Route::get('login', 'AuthSubscriber\LoginController@showLoginForm')->name('subscriber.login');
    Route::post('login', 'AuthSubscriber\LoginController@login');
    Route::post('logout', 'AuthSubscriber\LoginController@logout')->name('subscriber.logout');
    Route::get('password/reset', 'AuthSubscriber\ForgotPasswordController@showLinkRequestForm')->name('subscriber.password.request');
    Route::post('password/email', 'AuthSubscriber\ForgotPasswordController@sendResetLinkEmail')->name('subscriber.password.email');
    Route::get('password/reset/{token}', 'AuthSubscriber\ResetPasswordController@showResetForm')->name('subscriber.password.reset');
    Route::post('password/reset', 'AuthSubscriber\ResetPasswordController@reset')->name('subscriber.password.update');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth:subscriber'], function () {
    Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
        Route::get('/', 'DashboardController@formateurIndex')->name('formateur.index');
        Route::prefix('formation/{url}')->group(function () {
            Route::get('/', 'FormationController@formationSubscriber')->name('formateur.formation');
            Route::prefix('module/{module}')->group(function () {
                Route::get('/', 'ModuleController@moduleSubscriber')->name('formateur.module');
                Route::get('chapter/{chapter}', 'ChapterController@chapterSubscriber')->name('formateur.chapter');
            });
        });
    });
});

Route::group(['middleware' => ['auth:web', 'verified']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('mailservers', 'MailserverController');
    Route::resource('senders', 'SenderController');
    Route::resource('newsletters', 'NewsletterController');
    Route::resource('tags', 'TagController');
    Route::resource('subscribers', 'SubscriberController');
    Route::resource('forms', 'FormController');
    Route::resource('schedules', 'ScheduleController');
    Route::resource('campaigns', 'CampaignController');
    Route::resource('formations', 'FormationController');
    Route::resource('fields', 'FieldController');

    Route::prefix('formation/{formation}')->group(function () {
        Route::post('students', 'FormationController@storeStudents')->name('students.store');
        Route::get('students', 'FormationController@indexStudents')->name('students.index');
        Route::get('students/edit', 'FormationController@editStudents')->name('students.edit');
        Route::resource('modules', 'ModuleController');
        Route::prefix('module/{module}')->group(function () {
            Route::resource('chapters', 'ChapterController');
            Route::get('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwyg')->name('chapters.wysiwyg');
            Route::patch('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwygUpdate')->name('chapters.wysiwyg.update');
        });
    });

    Route::get('forms/{form}/wysiwyg', 'FormController@wysiwyg')->name('forms.wysiwyg');
    Route::patch('forms/{form}/wysiwyg', 'FormController@wysiwygUpdate')->name('forms.wysiwyg.update');
    Route::get('queues', 'QueueController@index')->name('queues.index');
    Route::get('queues/schedule/{schedule}', 'QueueController@showSchedule')->name('queues.schedule');
    Route::get('queues/subscriber/{subscriber}', 'QueueController@showSubscriber')->name('queues.subscriber');
    Route::get('queues/newsletter/{newsletter}', 'QueueController@showNewsletter')->name('queues.newsletter');
    Route::delete('queues/{queue}', 'QueueController@destroy')->name('queues.destroy');
    Route::get('campaigns/{campaign}/automate', 'CampaignController@automate')->name('campaigns.automate');
    Route::patch('campaigns/{campaign}/automate', 'CampaignController@automateUpdate')->name('campaigns.automate.update');
});

app/Chapter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    protected $fillable = [
        'name', 'module_id', 'desc', 'enabled', 'html'
    ];

    public function module()
    {
        return $this->belongsTo('App\Module');
    }
}

app/Http/Controllers/ChapterController.php
<?php

namespace App\Http\Controllers;

use Gate;
use App\User;
use App\Module;
use App\Chapter;
use App\Formation;
use Illuminate\Http\Request;
use App\Events\ChapterCreated;
use Illuminate\Support\Facades\Auth;
use Javascript;

class ChapterController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Chapter::class);
    }

    public function index(Formation $formation, Module $module)
    {
        return view('chapter.index', ['formation' => $formation, 'module' => $module]);
    }

    public function create(Formation $formation, Module $module)
    {
        return view('chapter.create', ['formation' => $formation, 'module' => $module]);
    }

    public function store(Formation $formation, Module $module, Request $request)
    {
        $rules = [
            'name' => 'required',
        ];
        $request->validate($rules);
        $chapter = new Chapter($request->all());
        if (!$request->has('enabled')) {
            $chapter->enabled = false;
        }
        $chapter->module_id = $module->id;
        $chapter->save();
        event(new ChapterCreated($chapter));
        return redirect()->route('chapters.wysiwyg', ['formation' => $formation, 'module' => $module, 'chapter' => $chapter])->with('success', __('Chapitre créé'));
    }

    public function show(Formation $formation, Module $module, Chapter $chapter)
    {
        return view('chapter.show', ['formation' => $formation, 'module' => $module, 'chapter' => $chapter]);
    }

    public function edit(Formation $formation, Module $module, Chapter $chapter)
    {
        return view('chapter.edit', ['formation' => $formation, 'module' => $module, 'chapter' => $chapter]);
    }

    public function update(Formation $formation, Module $module, Request $request, Chapter $chapter)
    {
        $rules = [
            'name' => 'required',
        ];
        $request->validate($rules);
        if (!$request->has('enabled')) {
            $chapter->enabled = false;
        }
        $chapter->update($request->all());
        return redirect()->route('chapters.index', ['formation' => $formation, 'module' => $module])->with('success', __('Chapitre mis à jour'));
    }

    public function destroy(Formation $formation, Module $module, Chapter $chapter)
    {
        $chapter->delete();
        return redirect()->route('chapters.index', ['formation' => $formation, 'module' => $module])->with('success', __('Chapitre supprimé'));
    }

    public function wysiwyg(Formation $formation, Module $module, Chapter $chapter)
    {
        $this->authorize('update', $chapter);

        $data = $chapter;
        $submitUrl = route('chapters.wysiwyg.update', [$formation->id, $module->id, $chapter->id]);
        $exitUrl = route('chapters.index', [$formation->id, $module->id]);
        $tags = array_format_value_name(Auth::user()->tags);
        $fieldsArray = [
            [
                'value' => '',
                'name' => __('Choisir un champs')
            ],
            [
                'value' => 'email',
                'name' => __('Email')
            ]
        ];
        $fields = array_format_value_name(Auth::user()->fields, ['uniq_id', 'name'], $fieldsArray);
        Javascript::put([
            'submitUrl' => $submitUrl,
            'exitUrl' => $exitUrl,
            'tags' => $tags,
            'fields' => $fields
        ]);
        return view('wysiwyg', compact('data'));
    }

    public function wysiwygUpdate(Formation $formation, Module $module, Request $request, Chapter $chapter)
    {
        $chapter->html = $request->html;
        $chapter->save();
        return redirect()->route('chapters.index', ['formation' => $formation, 'module' => $module])->with('success', __('Chapitre mis à jour'));
    }

    public function chapterSubscriber($subdomain, $url, Module $module, Chapter $chapter)
    {
        $user = User::subdomain($subdomain)->firstOrFail();
        $formation = $user->formations()->byUrl($url)->firstOrFail();
        if (!$module ||
            !$formation->modules()->where('modules.id', $module->id)->exists() ||
            !$chapter ||
            !$module->chapters()->where('chapters.id', $chapter->id)->exists() ||
            Gate::denies('view-formation', $formation)
        ) {
            abort(404);
        } else {
            return view('chapter.show', compact('subdomain', 'url', 'formation', 'module', 'chapter'));
        }
    }
}

resources/views/chapter/create.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [
            __('Formation'), 
            $formation->name, 
            __('Module'),
            $module->name,
            __('Chapitre'),
            __('Nouveau')
        ], 'new_btn_link' => ''])
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-body">
                    {!! Form::open([ 'method'  => 'POST', 'route' => [ 'chapters.store', $formation->id, $module->id ], 'autocomplete' => 'off' ]) !!}
                        <div class="form-group">
                            {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('desc', __('Description'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('desc', null, ['class' => 'form-control'.($errors->has('desc') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('desc'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('desc') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            {!! Form::checkbox('enabled', true, true, ['class' => 'form-check-input'.($errors->has('enabled') ? ' is-invalid' : ''), 'id' => 'enabled']) !!}
                            {!! Form::label('enabled', __('Active'), ['class' => 'form-check-label']) !!}
                            @if ($errors->has('enabled'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('enabled') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/chapter/edit.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [
            __('Formation'), 
            $formation->name, 
            __('Module'),
            $module->name,
            __('Chapitre'),
            $chapter->name
        ], 'new_btn_link' => ''])
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-body">
                    {!! Form::open([ 'method'  => 'patch', 'route' => [ 'chapters.update', $formation->id, $module->id, $chapter->id ], 'autocomplete' => 'off']) !!}
                        <div class="form-group">
                            {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('name', $chapter->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('desc', __('Description'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('desc', $chapter->desc, ['class' => 'form-control'.($errors->has('desc') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('desc'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('desc') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            {!! Form::checkbox('enabled', true, $chapter->enabled, ['class' => 'form-check-input'.($errors->has('enabled') ? ' is-invalid' : ''), 'id' => 'enabled']) !!}
                            {!! Form::label('enabled', __('Active'), ['class' => 'form-check-label']) !!}
                            @if ($errors->has('enabled'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('enabled') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/chapter/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.page-header', ['breadcrumb' => [
            __('Formation'), 
            $formation->name, 
            __('Module'),
            $module->name,
            __('Chapitres')
        ], 'new_btn_link' => route('chapters.create', [$formation->id, $module->id])])

    <div class="table-responsive shadow">
        <table class="table table-striped">
            <thead class="thead-dark">
                        <tr>
                            <th>{!! __('Nom') !!}</th>
                            <th>{!! __('Active') !!}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($module->chapters as $row)
                        <tr class="trigger-options" data-toggle="tooltip" data-placement="top" data-html="true" title="{{ $row->desc }}">
                            <td><a href="{!! route('chapters.show', ['formation' => $formation->id, 'module' => $module->id, 'chapter' => $row->id]) !!}">{!! $row->name !!}</a></td>
                            <td>{!! $row->enabled !!}</td>
                            <td>
                                <div class="options-hover float-right">
                                    <a href="{!!route('chapters.wysiwyg', ['formation' => $formation->id, 'module' => $module->id, 'chapter' => $row->id])!!}"><i class="fas fa-file-alt text-dark"></i></a>
                                    <a href="{!!route('chapters.edit', ['formation' => $formation->id, 'module' => $module->id, 'chapter' => $row->id])!!}"><i class="fas fa-edit text-dark"></i></a>
                                    <i class="fas fa-trash-alt delete-submit-form text-dark"></i>
                                    {!! Form::open([ 'method'  => 'delete', 'route' => [ 'chapters.destroy', $formation->id, $module->id, $row->id ]]) !!}{!! Form::close() !!}
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/chapter/show.blade.php
@extends('layouts.'.( auth()->guard('subscriber')->check() ? 'subscriber' : 'app'))

@section('content')
<div id="formation-header">
        <div class="row">
            <div class="col-md-3">
                <div class="user-info">
                    <img src="{{asset('img/profil-photo.png')}}" class="img-thumbnail rounded-circle profil-photo" alt="">
                    {{ $chapter->module->formation->user->name }}
                </div>
            </div>
            <div class="col-md-9">
                <div class="formation-title">
                    <h1>{{$chapter->module->formation->name}}</h1>
                    <h2>{{$chapter->module->name}}</h2>
                    <h3>{{$chapter->name}}</h3>
                </div>
            </div>
        </div>
    </div>
<div class="row">
    <div class="col-md-3">
        <div id="left" class="shadow">
            <div id="formation-title">
                {{$chapter->module->formation->name}}
            </div>

            <ul class="nav menu">
                {{-- MODULES --}}
                @foreach($chapter->module->formation->modules as $rowModule)
                <li class="module parent">
                    <div>
                        <span data-toggle="collapse" data-target="#module{{$rowModule->id}}" aria-expanded="{{$rowModule->id == $chapter->module->id ? 'true' : 'false'}}" aria-controls="module{{$rowModule->id}}" class="sign {{$rowModule->id == $chapter->module->id ? '' : 'collapsed'}}"><i class="fas fa-{{$rowModule->id == $chapter->module->id ? 'minus' : 'plus'}}"></i></span>
                        <a href="{{ auth()->guard('subscriber')->check() ? route('formateur.module', ['subdomain' => $subdomain, 'url' => $url, 'module' => $rowModule->id]) : route('modules.show', ['formation' => $rowModule->formation->id, 'module' => $rowModule->id]) }}"><span class="lbl">{{$rowModule->name}}</span></a>
                    </div>
                    <ul class="children nav-child unstyled small collapse {{$rowModule->id == $chapter->module->id ? 'show' : ''}}" id="module{{$rowModule->id}}">
                        {{-- CHAPTERS --}}
                        @foreach($rowModule->chapters as $rowChapter)
                        <li class="chapter {{$rowChapter->id == $chapter->id ? 'active' : ''}}">
                            <a class="" href="{{ auth()->guard('subscriber')->check() ? route('formateur.chapter', ['subdomain' => $subdomain, 'url' => $url, 'module' => $rowChapter->module->id, 'chapter' => $rowChapter->id]) : route('chapters.show', ['formation' => $rowChapter->module->formation->id, 'module' => $rowChapter->module->id, 'chapter' => $rowChapter->id]) }}">
                                <span class="sign"><i class="fas fa-play"></i></span>
                                <span class="lbl">{{$rowChapter->name}}</span>
                            </a>
                        </li>
                        @endforeach
                    </ul>
                </li>
                @endforeach
            </ul>
        </div>
    </div>
    <div class="col-md-9">
        <div class="shadow">
            {!! $chapter->html !!}
        </div>
    </div>
</div>
@endsection