routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('subdomain', '^((?!www|mailing).)*$');

Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
    Route::get('login', 'AuthSubscriber\LoginController@showLoginForm')->name('subscriber.login');
    Route::post('login', 'AuthSubscriber\LoginController@login');
    Route::post('logout', 'AuthSubscriber\LoginController@logout')->name('subscriber.logout');
    Route::get('password/reset', 'AuthSubscriber\ForgotPasswordController@showLinkRequestForm')->name('subscriber.password.request');
    Route::post('password/email', 'AuthSubscriber\ForgotPasswordController@sendResetLinkEmail')->name('subscriber.password.email');
    Route::get('password/reset/{token}', 'AuthSubscriber\ResetPasswordController@showResetForm')->name('subscriber.password.reset');
    Route::post('password/reset', 'AuthSubscriber\ResetPasswordController@reset')->name('subscriber.password.update');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth:subscriber'], function () {
    Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
        Route::get('/', 'DashboardController@formateurIndex')->name('formateur.index');
        Route::prefix('formation/{url}')->group(function () {
            Route::get('/', 'FormationController@formationSubscriber')->name('formateur.formation');
            Route::prefix('module/{module}')->group(function () {
                Route::get('/', 'ModuleController@moduleSubscriber')->name('formateur.module');
                Route::get('chapter/{chapter}', 'ChapterController@chapterSubscriber')->name('formateur.chapter');
            });
        });
    });
});

Route::group(['middleware' => ['auth:web', 'verified']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('mailservers', 'MailserverController');
    Route::resource('senders', 'SenderController');
    Route::resource('newsletters', 'NewsletterController');
    Route::resource('tags', 'TagController');
    Route::resource('subscribers', 'SubscriberController');
    Route::resource('forms', 'FormController');
    Route::resource('schedules', 'ScheduleController');
    Route::resource('campaigns', 'CampaignController');
    Route::resource('formations', 'FormationController');
    Route::resource('fields', 'FieldController');

    Route::prefix('formation/{formation}')->group(function () {
        Route::post('students', 'FormationController@storeStudents')->name('students.store');
        Route::get('students', 'FormationController@indexStudents')->name('students.index');
        Route::get('students/edit', 'FormationController@editStudents')->name('students.edit');
        Route::resource('modules', 'ModuleController');
        Route::prefix('module/{module}')->group(function () {
            Route::resource('chapters', 'ChapterController');
            Route::get('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwyg')->name('chapters.wysiwyg');
            Route::patch('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwygUpdate')->name('chapters.wysiwyg.update');
        });
    });

    Route::get('forms/{form}/wysiwyg', 'FormController@wysiwyg')->name('forms.wysiwyg');
    Route::patch('forms/{form}/wysiwyg', 'FormController@wysiwygUpdate')->name('forms.wysiwyg.update');
    Route::get('queues', 'QueueController@index')->name('queues.index');
    Route::get('queues/schedule/{schedule}', 'QueueController@showSchedule')->name('queues.schedule');
    Route::get('queues/subscriber/{subscriber}', 'QueueController@showSubscriber')->name('queues.subscriber');
    Route::get('queues/newsletter/{newsletter}', 'QueueController@showNewsletter')->name('queues.newsletter');
    Route::delete('queues/{queue}', 'QueueController@destroy')->name('queues.destroy');
    Route::get('campaigns/{campaign}/automate', 'CampaignController@automate')->name('campaigns.automate');
    Route::patch('campaigns/{campaign}/automate', 'CampaignController@automateUpdate')->name('campaigns.automate.update');
});

app/Schedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Schedule extends Model
{
    protected $fillable = [
        'name', 'newsletter_id', 'user_id', 'tags_type', 'queued_at', 'queued'
    ];

    public function delete()
    {
        $this->queues()->delete();
        parent::delete();
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function newsletter()
    {
        return $this->belongsTo('App\Newsletter');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function queues()
    {
        return $this->hasMany('App\Queue');
    }

    public function scopeToQueued($query)
    {
        return $query->where('queued', false)->whereDate('queued_at', '<=', Carbon::now()->toDateTimeString());
    }
}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Schedule;
use Illuminate\Http\Request;
use Auth;

class ScheduleController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Schedule::class);
    }

    public function index()
    {
        return view('schedule.index');
    }

    public function create()
    {
        return view('schedule.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'newsletter_id' => 'required|in:'.implode(',', Auth::user()->newsletters()->pluck('newsletters.id')->toArray()),
            'tags_type' => 'required|in:alltags,all,once',
            'tags' => 'required_unless:tags_type,alltags',
            'queued_at' => 'required|date_format:"Y-m-d H:i:s"',
        ];
        $request->validate($rules);
        $schedule = new Schedule($request->all());
        $schedule->user_id = Auth::id();
        $schedule->save();
        $schedule->tags()->sync($request->tags);
        return redirect()->route('schedules.index')->with('success', __('Plannification créée'));
    }

    public function show(Schedule $schedule)
    {
        return view('schedule.show', ['schedule' => $schedule]);
    }

    public function edit(Schedule $schedule)
    {
        return view('schedule.edit', ['schedule' => $schedule]);
    }

    public function update(Request $request, Schedule $schedule)
    {
        $rules = [
            'newsletter_id' => 'required|in:'.implode(',', Auth::user()->newsletters()->pluck('newsletters.id')->toArray()),
            'tags_type' => 'required|in:alltags,all,once',
            'tags' => 'required_unless:tags_type,alltags',
            'queued_at' => 'required|date_format:"Y-m-d H:i:s"',
        ];
        $request->validate($rules);
        $schedule->update($request->all());
        $schedule->tags()->sync($request->tags);
        return redirect()->route('schedules.index')->with('success', __('Plannification mise à jour'));
    }

    public function destroy(Schedule $schedule)
    {
        $schedule->delete();
        return redirect()->route('schedules.index')->with('success', __('Plannification supprimée'));
    }
}

resources/views/schedule/create.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Plannification'), __('Nouveau')], 'new_btn_link' => ''])
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow">
            <div class="card-body">
                {!! Form::open([ 'method'  => 'POST', 'route' => [ 'schedules.store' ], 'autocomplete' => 'off' ]) !!}
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('newsletter_id', __('Newsletter'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('newsletter_id', Auth::user()->newsletters->where('type', 'news')->pluck('name', 'id'), null, ['class' => 'form-control'.($errors->has('newsletter_id') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('newsletter_id'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('newsletter_id') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('tags', __('Tags'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('tags_type', ['alltags' => __('Tous les tags'), 'all' => __('Qui ont tous les tags suivants'), 'once' => __('Qui ont au moins un des tags suivants'),], null, ['class' => 'form-control'.($errors->has('tags_type') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('tags_type'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('tags_type') !!}</strong>
                            </span>
                        @endif
                        {!! Form::select('tags[]', Auth::user()->tags->pluck('name', 'id'), null, ['class' => 'multi-tag form-control'.($errors->has('tags') ? ' is-invalid' : ''), 'multiple' => 'multiple', 'disabled' => 'disabled']) !!}
                        @if ($errors->has('tags'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('tags') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('queued_at', __('Date d\'envoi'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('queued_at', null, ['class' => 'form-control datetimepicker'.($errors->has('queued_at') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('queued_at'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('queued_at') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group text-right">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        $(function(){
            var tags_type = $('select[name="tags_type"]').val();
            if(tags_type == 'alltags'){
                $('select[name="tags[]"]').prop('disabled', true);
            }else{
                $('select[name="tags[]"]').prop('disabled', false);
            }

            $('select[name="tags_type"]').change(function(){
                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })
        })
    </script>
@endsection

resources/views/schedule/edit.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Plannification'), $schedule->name], 'new_btn_link' => ''])
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow">
            <div class="card-body">
                {!! Form::open([ 'method'  => 'patch', 'route' => [ 'schedules.update', $schedule->id ], 'autocomplete' => 'off' ]) !!}
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', $schedule->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('newsletter_id', __('Newsletter'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('newsletter_id', Auth::user()->newsletters->where('type', 'news')->pluck('name', 'id'), $schedule->newsletter_id, ['class' => 'form-control'.($errors->has('newsletter_id') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('newsletter_id'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('newsletter_id') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('tags', __('Tags'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('tags_type', ['alltags' => __('Tous les tags'), 'all' => __('Qui ont tous les tags suivants'), 'once' => __('Qui ont au moins un des tags suivants'),], $schedule->tags_type, ['class' => 'form-control'.($errors->has('tags_type') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('tags_type'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('tags_type') !!}</strong>
                            </span>
                        @endif
                        {!! Form::select('tags[]', Auth::user()->tags->pluck('name', 'id'), $schedule->tags, ['class' => 'form-control'.($errors->has('tags') ? ' is-invalid' : ''), 'multiple' => 'multiple', 'disabled' => 'disabled']) !!}
                        @if ($errors->has('tags'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('tags') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('queued_at', __('Date d\'envoi'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('queued_at', $schedule->queued_at, ['class' => 'form-control datetimepicker'.($errors->has('queued_at') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('queued_at'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('queued_at') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group text-right">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        $(function(){
            var tags_type = $('select[name="tags_type"]').val();
            if(tags_type == 'alltags'){
                $('select[name="tags[]"]').prop('disabled', true);
            }else{
                $('select[name="tags[]"]').prop('disabled', false);
            }

            $('select[name="tags_type"]').change(function(){
                var tags_type = $('select[name="tags_type"]').val();
                if(tags_type == 'alltags'){
                    $('select[name="tags[]"]').prop('disabled', true);
                }else{
                    $('select[name="tags[]"]').prop('disabled', false);
                }
            })
        })
    </script>
@endsection

resources/views/schedule/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.page-header', ['breadcrumb' => [__('Plannifications')], 'new_btn_link' => route('schedules.create')])

    <div class="table-responsive shadow">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>{!! __('Nom') !!}</th>
                    <th>{!! __('Newsletter') !!}</th>
                    <th>{!! __('Tags') !!}</th>
                    <th>{!! __('Date d\'envoi') !!}</th>
                    <th>{!! __('Etat') !!}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Auth::user()->schedules as $row)
                <tr class="trigger-options">
                    <td>{!! $row->name !!}</td>
                    <td>{!! $row->newsletter->name !!}</td>
                    <td>
                        {!! $row->tags_type == 'alltags' ? __('Tous les tags') : ($row->tags_type == 'once' ? __('Qui ont un des tags suivants') : __('Qui ont tous les tags suivants')) !!}
                        @if($row->tags_type != 'alltags')
                        @foreach ($row->tags as $tag)
                            <div class="tag">{!! $tag->name !!}</div>
                        @endforeach
                        @endif
                    </td>
                    <td>{!! $row->queued_at !!}</td>
                    <td>{!! $row->queued ? __('Envoyé') : __('En attente') !!}</td>
                    <td>
                        <div class="options-hover float-right">
                            @if(!$row->queued)
                                <a data-toggle="tooltip" data-placement="top" title="{!! __('Modifier') !!}" href="{!!route('schedules.edit', $row->id)!!}"><i class="fas fa-edit text-dark"></i></a>
                            @else
                                <a data-toggle="tooltip" data-placement="top" title="{!! __('Queue') !!}" href="{!!route('queues.schedule', $row->id)!!}"><i class="fas fa-layer-group text-dark"></i></a>
                            @endif
                            <i class="fas fa-trash-alt delete-submit-form text-dark"></i>
                            {!! Form::open([ 'method'  => 'delete', 'route' => [ 'schedules.destroy', $row->id ] ]) !!}{!! Form::close() !!}
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection