routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('subdomain', '^((?!www|mailing).)*$');

Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
    Route::get('login', 'AuthSubscriber\LoginController@showLoginForm')->name('subscriber.login');
    Route::post('login', 'AuthSubscriber\LoginController@login');
    Route::post('logout', 'AuthSubscriber\LoginController@logout')->name('subscriber.logout');
    Route::get('password/reset', 'AuthSubscriber\ForgotPasswordController@showLinkRequestForm')->name('subscriber.password.request');
    Route::post('password/email', 'AuthSubscriber\ForgotPasswordController@sendResetLinkEmail')->name('subscriber.password.email');
    Route::get('password/reset/{token}', 'AuthSubscriber\ResetPasswordController@showResetForm')->name('subscriber.password.reset');
    Route::post('password/reset', 'AuthSubscriber\ResetPasswordController@reset')->name('subscriber.password.update');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth:subscriber'], function () {
    Route::domain('{subdomain}.'.(env('APP_DOMAIN') !== null ? env('APP_DOMAIN') : 'joudia.io'))->group(function () {
        Route::get('/', 'DashboardController@formateurIndex')->name('formateur.index');
        Route::prefix('formation/{url}')->group(function () {
            Route::get('/', 'FormationController@formationSubscriber')->name('formateur.formation');
            Route::prefix('module/{module}')->group(function () {
                Route::get('/', 'ModuleController@moduleSubscriber')->name('formateur.module');
                Route::get('chapter/{chapter}', 'ChapterController@chapterSubscriber')->name('formateur.chapter');
            });
        });
    });
});

Route::group(['middleware' => ['auth:web', 'verified']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('mailservers', 'MailserverController');
    Route::resource('senders', 'SenderController');
    Route::resource('newsletters', 'NewsletterController');
    Route::resource('tags', 'TagController');
    Route::resource('subscribers', 'SubscriberController');
    Route::resource('forms', 'FormController');
    Route::resource('schedules', 'ScheduleController');
    Route::resource('campaigns', 'CampaignController');
    Route::resource('formations', 'FormationController');
    Route::resource('fields', 'FieldController');

    Route::prefix('formation/{formation}')->group(function () {
        Route::post('students', 'FormationController@storeStudents')->name('students.store');
        Route::get('students', 'FormationController@indexStudents')->name('students.index');
        Route::get('students/edit', 'FormationController@editStudents')->name('students.edit');
        Route::resource('modules', 'ModuleController');
        Route::prefix('module/{module}')->group(function () {
            Route::resource('chapters', 'ChapterController');
            Route::get('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwyg')->name('chapters.wysiwyg');
            Route::patch('chapters/{chapter}/wysiwyg', 'ChapterController@wysiwygUpdate')->name('chapters.wysiwyg.update');
        });
    });

    Route::get('forms/{form}/wysiwyg', 'FormController@wysiwyg')->name('forms.wysiwyg');
    Route::patch('forms/{form}/wysiwyg', 'FormController@wysiwygUpdate')->name('forms.wysiwyg.update');
    Route::get('queues', 'QueueController@index')->name('queues.index');
    Route::get('queues/schedule/{schedule}', 'QueueController@showSchedule')->name('queues.schedule');
    Route::get('queues/subscriber/{subscriber}', 'QueueController@showSubscriber')->name('queues.subscriber');
    Route::get('queues/newsletter/{newsletter}', 'QueueController@showNewsletter')->name('queues.newsletter');
    Route::delete('queues/{queue}', 'QueueController@destroy')->name('queues.destroy');
    Route::get('campaigns/{campaign}/automate', 'CampaignController@automate')->name('campaigns.automate');
    Route::patch('campaigns/{campaign}/automate', 'CampaignController@automateUpdate')->name('campaigns.automate.update');
});

app/Formation.php
<?php

namespace App;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;

class Formation extends Model
{
    protected $fillable = [
        'name', 'user_id', 'desc', 'url', 'img', 'enabled'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function modules()
    {
        return $this->hasMany('App\Module');
    }

    public function subscribers()
    {
        return $this->belongsToMany('App\Subscriber')->withTimestamps();
    }

    public function scopeByUrl($query, $url)
    {
        return $query->where(['url' => $url, 'enabled' => 1]);
    }

    public function scopeOwned($query)
    {
        return $query->where('formations.user_id', Auth::id());
    }
}

app/Http/Controllers/Api/FormationController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FormationController extends Controller
{
    public function index(Request $request)
    {
        return response()->json($request->user()->formations);
    }
}

app/Http/Controllers/FormationController.php
<?php

namespace App\Http\Controllers;

use App\Formation;
use App\Subscriber;
use App\User;
use Illuminate\Http\Request;
use Auth;
use Gate;
use App\Events\SubscriberAddedToFormation;

class FormationController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Formation::class);
    }

    public function index()
    {
        return view('formation.index');
    }

    public function create()
    {
        $subscribers = Subscriber::owned()->get();
        return view('formation.create', ['subscribers' => $subscribers]);
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'url' => 'required|unique:formations,url,NULL,id,user_id,'.Auth::id(),
            'img' => 'image|max:2048',
        ];
        $request->validate($rules);
        $formation = new Formation($request->except('img'));
        $formation->user_id = Auth::id();
        if ($request->hasFile('img')) {
            $request->img->store('public/'.Auth::id().'/images');
            $formation->img = $request->img->hashName();
        }
        if (!$request->has('enabled')) {
            $formation->enabled = false;
        }
        $formation->save();
        $new_users = $formation->subscribers()->sync($request->subscribers);
        $new_subscribed_account = Subscriber::whereIn('id', $new_users['attached'])->get();
        foreach ($new_subscribed_account as $subscriber) {
            event(new SubscriberAddedToFormation($subscriber, $formation));
        }
        return redirect()->route('formations.index')->with('success', __('Formation créée'));
    }

    public function show(Formation $formation)
    {
        return view('formation.show', ['formation' => $formation]);
    }

    public function edit(Formation $formation)
    {
        $subscribers = Subscriber::owned()->get();
        return view('formation.edit', ['formation' => $formation, 'subscribers' => $subscribers]);
    }

    public function update(Request $request, Formation $formation)
    {
        $rules = [
            'name' => 'required',
            'url' => 'required|unique:formations,url,'.$formation->id.',id,user_id,'.Auth::id(),
            'img' => 'image|max:2048',
        ];
        $request->validate($rules);
        if ($request->hasFile('img')) {
            $request->img->store('public/'.Auth::id().'/images');
            $formation->img = $request->img->hashName();
        }
        if (!$request->has('enabled')) {
            $formation->enabled = false;
        }
        $formation->update($request->except('img'));
        $new_users = $formation->subscribers()->sync($request->subscribers);
        $new_subscribed_account = Subscriber::whereIn('id', $new_users['attached'])->get();
        foreach ($new_subscribed_account as $subscriber) {
            event(new SubscriberAddedToFormation($subscriber, $formation));
        }
        return redirect()->route('formations.index')->with('success', __('Formation créée'));
    }

    public function destroy(Formation $formation)
    {
        $formation->delete();
        return redirect()->route('formations.index')->with('success', __('Formulaire supprimée'));
    }

    public function formationSubscriber($subdomain, $url)
    {
        $user = User::subdomain($subdomain)->firstOrFail();
        $formation = $user->formations()->byUrl($url)->firstOrFail();
        if (Gate::allows('view-formation', $formation)) {
            return view('formation.show', ['formation' => $formation, 'subdomain' => $subdomain, 'url' => $url]);
        } else {
            abort(404);
        }
    }
}

resources/views/formation/create.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Formation'), __('Nouveau')], 'new_btn_link' => ''])
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-body">
                    {!! Form::open([ 'method'  => 'POST', 'route' => [ 'formations.store' ], 'autocomplete' => 'off', 'files' => true ]) !!}
                        <div class="form-group">
                            {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('desc', __('Description'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('desc', null, ['class' => 'form-control'.($errors->has('desc') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('desc'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('desc') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('url', __('Lien'), ['class' => 'col-form-label text-md-right']) !!}
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">{{route('formateur.formation', [Auth::user()->domain, ''])}}/</div>
                                </div>
                                {!! Form::text('url', null, ['class' => 'form-control'.($errors->has('url') ? ' is-invalid' : '')]) !!}
                                @if ($errors->has('url'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('url') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-file">
                                {!! Form::file('img', ['class' => 'custom-file-input'.($errors->has('img') ? ' is-invalid' : '')]) !!}
                                {!! Form::label('img', __('Image'), ['class' => 'custom-file-label']) !!}
                                @if ($errors->has('img'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('img') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('subscribers', __('Elèves'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('subscribers[]', $subscribers->pluck('email', 'id'), null, ['class' => 'tag form-control'.($errors->has('subscribers') ? ' is-invalid' : ''), 'multiple' => 'multiple']) !!}
                            @if ($errors->has('subscribers'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('subscribers') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            {!! Form::checkbox('enabled', true, true, ['class' => 'form-check-input'.($errors->has('enabled') ? ' is-invalid' : ''), 'id' => 'enabled']) !!}
                            {!! Form::label('enabled', __('Active'), ['class' => 'form-check-label']) !!}
                            @if ($errors->has('enabled'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('enabled') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mb-0 text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/formation/edit.blade.php
@extends('layouts.app')

@section('content')
@include('components.page-header', ['breadcrumb' => [__('Formation'), $formation->name], 'new_btn_link' => ''])
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-body">
                    {!! Form::open([ 'method'  => 'patch', 'route' => [ 'formations.update', $formation->id ], 'autocomplete' => 'off', 'files' => true ]) !!}
                        <div class="form-group">
                            {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('name', $formation->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('name') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('desc', __('Description'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('desc', $formation->desc, ['class' => 'form-control'.($errors->has('desc') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('desc'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('desc') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            {!! Form::label('url', __('Lien'), ['class' => 'col-form-label text-md-right']) !!}
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">{{route('formateur.formation', [Auth::user()->domain, ''])}}/</div>
                                </div>
                                {!! Form::text('url', $formation->url, ['class' => 'form-control'.($errors->has('url') ? ' is-invalid' : '')]) !!}
                                @if ($errors->has('url'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('url') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-file">
                                {!! Form::file('img', ['class' => 'custom-file-input'.($errors->has('img') ? ' is-invalid' : '')]) !!}
                                {!! Form::label('img', __('Image'), ['class' => 'custom-file-label']) !!}
                                @if ($errors->has('img'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{!! $errors->first('img') !!}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('subscribers', __('Elèves'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('subscribers[]', $subscribers->pluck('email', 'id'), $formation->subscribers, ['class' => 'tag form-control'.($errors->has('subscribers') ? ' is-invalid' : ''), 'multiple' => 'multiple']) !!}
                            @if ($errors->has('subscribers'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('subscribers') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            {!! Form::checkbox('enabled', true, $formation->enabled, ['class' => 'form-check-input'.($errors->has('enabled') ? ' is-invalid' : ''), 'id' => 'enabled']) !!}
                            {!! Form::label('enabled', __('Active'), ['class' => 'form-check-label']) !!}
                            @if ($errors->has('enabled'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('enabled') !!}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mb-0 text-right">
                            {!! Form::submit(__('Valider'), ['class' => 'btn btn-primary']) !!}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/formation/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.page-header', ['breadcrumb' => [__('Formations')], 'new_btn_link' => route('formations.create')])

    <div class="table-responsive shadow">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>{!! __('Nom') !!}</th>
                    <th>{!! __('Lien') !!}</th>
                    <th>{!! __('Active') !!}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Auth::user()->formations as $row)
                <tr class="trigger-options" data-toggle="tooltip" data-placement="top" data-html="true" title="{!! $row->desc !!}">
                    <td><a href="{!! route('modules.index', $row->id) !!}">{!! $row->img ? Html::image(asset('storage/'.Auth::id().'/images/'.$row->img), 'img '.$row->name, ['class' => 'img-fluid img-thumbnail formation-thumbnail']) : NULL !!} {!! $row->name !!}</a></td>
                    <td>
                        <div class="input-group">
                            <input id="url-{{ $row->id }}" type="text" class="form-control" aria-describedby="url-{{ $row->id }}-btn" value="{!! route('formateur.formation', [Auth::user()->domain, $row->url]) !!}">
                            <div class="input-group-append">
                                <button data-clipboard-target="#url-{{ $row->id }}" class="btn btn-outline-secondary copy-clipboard" type="button" id="url-{{ $row->id }}-btn">{!! __('Copier') !!}</button>
                            </div>
                        </div>
                    </td>
                    <td>{!! $row->enabled ? 'Oui' : 'Non' !!}</td>
                    <td>
                        <div class="options-hover float-right">
                            <a href="{!!route('formations.edit', $row->id)!!}"><i class="fas fa-edit text-dark"></i></a>
                            <i class="fas fa-trash-alt delete-submit-form text-dark"></i>
                            {!! Form::open([ 'method'  => 'delete', 'route' => [ 'formations.destroy', $row->id ] ]) !!}{!! Form::close() !!}
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/formation/show.blade.php
@extends('layouts.'.( auth()->guard('subscriber')->check() ? 'subscriber' : 'app'))

@section('content')
<div id="formation-header">
    <div class="row">
        <div class="col-md-3">
            <div class="user-info">
                <img src="{{asset('img/profil-photo.png')}}" class="img-thumbnail rounded-circle profil-photo" alt="">
                {{ $formation->user->name }}
            </div>
        </div>
        <div class="col-md-9">
            <div class="formation-title">
                <h1>{{$formation->name}}</h1>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div id="left" class="shadow">
            <div id="formation-title">
                {{$formation->name}}
            </div>

            <ul class="nav menu">
                {{-- MODULES --}}
                @foreach($formation->modules as $rowModule)
                <li class="module parent">
                    <div>
                        <span data-toggle="collapse" data-target="#module{{$rowModule->id}}" aria-expanded="false" aria-controls="module{{$rowModule->id}}" class="sign collapsed"><i class="fas fa-plus"></i></span>
                        <a href="{{ auth()->guard('subscriber')->check() ? route('formateur.module', ['subdomain' => $subdomain, 'url' => $url, 'module' => $rowModule->id]) : route('modules.show', ['formation' => $rowModule->formation->id, 'module' => $rowModule->id]) }}"><span class="lbl">{{$rowModule->name}}</span></a>
                    </div>
                    <ul class="children nav-child unstyled small collapse" id="module{{$rowModule->id}}">
                        {{-- CHAPTERS --}}
                        @foreach($rowModule->chapters as $rowChapter)
                        <li class="chapter">
                            <a class="" href="{{ auth()->guard('subscriber')->check() ? route('formateur.chapter', ['subdomain' => $subdomain, 'url' => $url, 'module' => $rowChapter->module->id, 'chapter' => $rowChapter->id]) : route('chapters.show', ['formation' => $rowChapter->module->formation->id, 'module' => $rowChapter->module->id, 'chapter' => $rowChapter->id]) }}">
                                <span class="sign"><i class="fas fa-play"></i></span>
                                <span class="lbl">{{$rowChapter->name}}</span>
                            </a>
                        </li>
                        @endforeach
                    </ul>
                </li>
                @endforeach
            </ul>
        </div>
    </div>
    <div class="col-md-9">
        <div class="shadow">
            {!! $formation->desc !!}
        </div>
    </div>
</div>
@endsection

resources/views/formation/students.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div id="main-title" class="col-md-12">
        <div class="float-left">
            <div id="page-title">{!! __('Formation') !!}</div>
        </div>
        <div class="float-right">
            
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                {!! Form::open([ 'method'  => 'POST', 'route' => [ 'formations.store' ], 'autocomplete' => 'off', 'files' => true ]) !!}
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('desc', __('Description'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::textarea('desc', null, ['class' => 'form-control'.($errors->has('desc') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('desc'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('desc') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('url', __('Lien'), ['class' => 'col-form-label text-md-right']) !!}
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">{{route('formateur.formationraw', Auth::user()->domain)}}/</div>
                            </div>
                            {!! Form::text('url', null, ['class' => 'form-control'.($errors->has('url') ? ' is-invalid' : '')]) !!}
                            @if ($errors->has('url'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('url') !!}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="custom-file">
                            {!! Form::file('img', ['class' => 'custom-file-input'.($errors->has('img') ? ' is-invalid' : '')]) !!}
                            {!! Form::label('img', __('Image'), ['class' => 'custom-file-label']) !!}
                            @if ($errors->has('img'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $errors->first('img') !!}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group form-check">
                        {!! Form::checkbox('enabled', true, true, ['class' => 'form-check-input'.($errors->has('enabled') ? ' is-invalid' : ''), 'id' => 'enabled']) !!}
                        {!! Form::label('enabled', __('Active'), ['class' => 'form-check-label']) !!}
                        @if ($errors->has('enabled'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('enabled') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::submit(__('Valider'), ['class' => 'btn bg-primary-theme']) !!}
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection